// Testi modificabili dell'applicazione
export const TEXTS = {
  app: {
    name: "Veredoc",
    tagline: "I tuoi documenti, spiegati in chiaro.",
    description: "Carica una bolletta per scoprire se stai pagando troppo, o una busta paga per capire ogni voce. Nessun inserimento manuale — basta il PDF.",
  },
  upload: {
    title: "Analizza un documento",
    subtitle: "Carica una bolletta o una busta paga. L'analisi richiede circa 30 secondi.",
    dragDrop: "Trascina il file qui oppure",
    browse: "sfoglia",
    fileTypes: "PDF, JPG, PNG — max 10MB",
    analyzing: "Analisi in corso...",
    analyzeButton: "Analizza documento",
  },
  dashboard: {
    title: "I tuoi documenti",
    subtitle: "Storico delle analisi effettuate.",
    empty: "Nessun documento analizzato. Carica il primo.",
    newAnalysis: "Nuova analisi",
  },
  analysis: {
    savingBanner: "Risparmio stimato",
    perYear: "l'anno",
    payingTooMuch: "Stai pagando il {pct}% in più della media di mercato.",
    goodDeal: "Stai pagando in linea con il mercato.",
    suggestedOffers: "Offerte più convenienti",
    switchNow: "Vedi offerta",
    noMarketData: "Dati di mercato non ancora disponibili per questa categoria.",
  },
  auth: {
    loginTitle: "Accedi a Veredoc",
    registerTitle: "Crea un account",
    emailLabel: "Email",
    passwordLabel: "Password",
    loginButton: "Accedi",
    registerButton: "Registrati",
    noAccount: "Non hai un account?",
    hasAccount: "Hai già un account?",
    signUp: "Registrati",
    signIn: "Accedi",
    forgotPassword: "Password dimenticata?",
  },
  forgotPassword: {
    title: "Recupera la password",
    subtitle: "Inserisci l'email del tuo account. Ti invieremo un link per reimpostare la password.",
    emailLabel: "Email",
    submitButton: "Invia istruzioni",
    confirmation: "Se l'indirizzo è registrato, riceverai un'email con le istruzioni.",
    backToLogin: "Torna al login",
  },
  resetPassword: {
    title: "Imposta una nuova password",
    subtitle: "Scegli una nuova password per il tuo account.",
    passwordLabel: "Nuova password",
    confirmPasswordLabel: "Conferma password",
    submitButton: "Reimposta password",
    passwordHint: "Minimo 8 caratteri.",
    passwordMismatch: "Le password non coincidono.",
    success: "Password aggiornata. Ora puoi accedere con la nuova password.",
    goToLogin: "Vai al login",
    checkingToken: "Verifica del link in corso...",
    invalidTokenTitle: "Link non valido o scaduto",
    invalidTokenSubtitle: "Il link per reimpostare la password non è valido oppure è scaduto.",
    requestNewLink: "Richiedi un nuovo link",
    missingToken: "Link non valido: token mancante.",
    errors: {
      missingFields: "Token e password sono obbligatori.",
      tooShort: "La password deve contenere almeno 8 caratteri.",
      invalidOrExpired: "Il link è scaduto o non è più valido. Richiedi un nuovo link.",
      generic: "Errore interno del server.",
    },
  },
  pricing: {
    title: "Prezzi semplici, senza sorprese",
    subtitle: "Scegli il piano più adatto a te. Nessun vincolo, cancella quando vuoi.",
    free: {
      badge: "GRATUITO",
      price: "€0",
      period: "sempre",
      features: [
        "Analisi di bollette luce, gas e internet",
        "Analisi buste paga",
        "Confronto con le offerte di mercato aggiornate",
        "10 analisi al mese",
      ],
      cta: "Inizia gratis",
    },
    pro: {
      badge: "PRO",
      popularBadge: "PIÙ POPOLARE",
      monthly: { label: "Mensile", price: "€2,49", period: "/mese" },
      annual: { label: "Annuale", price: "€19,90", period: "/anno", note: "€1,66/mese — risparmi il 33%" },
      features: [
        { text: "Tutto quello del piano gratuito" },
        { text: "30 analisi al mese" },
        { text: "Anonimizzatore documenti — il tuo PDF non lascia mai il dispositivo" },
        { text: "Storico completo dei tuoi documenti" },
        { text: "Export report in PDF", soon: true },
        { text: "Supporto prioritario", soon: true },
      ],
      cta: "Prova PRO",
      ctaNote: "Pagamento sicuro — cancella quando vuoi",
    },
    dataNote: "Non usiamo i tuoi documenti per addestrare modelli AI. I PDF vengono eliminati automaticamente dopo l'analisi.",
  },
};
