// Testi modificabili dell'applicazione
export const TEXTS = {
  app: {
    name: "Veredoc",
    tagline: "I tuoi documenti, spiegati in chiaro.",
    description: "Carica una bolletta per scoprire se stai pagando troppo, o una busta paga per capire ogni voce. Nessun inserimento manuale — basta il PDF.",
  },
  upload: {
    title: "Analizza un documento",
    subtitle: "Carica una bolletta o una busta paga. L'analisi richiede circa 30 secondi.",
    dragDrop: "Trascina il file qui oppure",
    browse: "sfoglia",
    fileTypes: "PDF, JPG, PNG — max 10MB",
    analyzing: "Analisi in corso...",
    analyzeButton: "Analizza documento",
  },
  dashboard: {
    title: "I tuoi documenti",
    subtitle: "Storico delle analisi effettuate.",
    empty: "Nessun documento analizzato. Carica il primo.",
    newAnalysis: "Nuova analisi",
  },
  analysis: {
    savingBanner: "Risparmio stimato",
    perYear: "l'anno",
    payingTooMuch: "Stai pagando il {pct}% in più della media di mercato.",
    goodDeal: "Stai pagando in linea con il mercato.",
    suggestedOffers: "Offerte più convenienti",
    switchNow: "Vedi offerta",
    noMarketData: "Dati di mercato non ancora disponibili per questa categoria.",
  },
  auth: {
    loginTitle: "Accedi a Veredoc",
    registerTitle: "Crea un account",
    emailLabel: "Email",
    passwordLabel: "Password",
    loginButton: "Accedi",
    registerButton: "Registrati",
    noAccount: "Non hai un account?",
    hasAccount: "Hai già un account?",
    signUp: "Registrati",
    signIn: "Accedi",
  },
  pricing: {
    title: "Prezzi semplici, senza sorprese",
    subtitle: "Scegli il piano più adatto a te. Nessun vincolo, cancella quando vuoi.",
    free: {
      badge: "GRATUITO",
      price: "€0",
      period: "sempre",
      features: [
        "Analisi di bollette luce, gas e internet",
        "Analisi buste paga",
        "Confronto con le offerte di mercato aggiornate",
        "10 analisi al mese",
      ],
      cta: "Inizia gratis",
    },
    pro: {
      badge: "PRO",
      popularBadge: "PIÙ POPOLARE",
      monthly: { label: "Mensile", price: "€2,49", period: "/mese" },
      annual: { label: "Annuale", price: "€19,90", period: "/anno", note: "€1,66/mese — risparmi il 33%" },
      features: [
        { text: "Tutto quello del piano gratuito" },
        { text: "30 analisi al mese" },
        { text: "Anonimizzatore documenti — il tuo PDF non lascia mai il dispositivo" },
        { text: "Storico completo dei tuoi documenti" },
        { text: "Export report in PDF", soon: true },
        { text: "Supporto prioritario", soon: true },
      ],
      cta: "Prova PRO",
      ctaNote: "Pagamento sicuro — cancella quando vuoi",
    },
    dataNote: "Non usiamo i tuoi documenti per addestrare modelli AI. I PDF vengono eliminati automaticamente dopo l'analisi.",
  },
};
